import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import time
import math
import random
import os
import json

class StrokeNeuronLayer(nn.Module):
    """
    V50: Parametric Stroke Neurons.
    Each neuron is defined by 3 points (P0, P1, P2) forming a Quadratic Bezier Curve.
    The weights are generated by rasterizing the curve in a differentiable way.
    """
    def __init__(self, num_neurons=128, device='cpu'):
        super().__init__()
        self.num_neurons = num_neurons
        self.size = 28
        self.device = device
        
        # Trainable parameters: 3 points (x, y) per neuron. Total 6 params/neuron.
        # Initialized randomly within the 28x28 space.
        self.points = nn.Parameter(torch.rand(num_neurons, 3, 2) * 28.0)
        
        # Width of the positive stroke and the negative surround
        self.sigma_pos = 1.5
        self.sigma_neg = 3.0
        
        # Pre-compute grid coordinates
        y, x = torch.meshgrid(torch.linspace(0, 27, 28), torch.linspace(0, 27, 28), indexing='ij')
        self.register_buffer("grid", torch.stack([x, y], dim=-1).view(1, 784, 2)) # (1, 784, 2)

    def get_masks(self):
        """Generates the 28x28 masks from the bezier points."""
        # 1. Sample points along the Bezier curve
        # t is from 0 to 1 (12 steps)
        t = torch.linspace(0, 1, 12, device=self.points.device).view(1, 12, 1)
        
        p0 = self.points[:, 0:1, :] # (N, 1, 2)
        p1 = self.points[:, 1:2, :] # (N, 1, 2)
        p2 = self.points[:, 2:3, :] # (N, 1, 2)
        
        # Quadratic Bezier: (1-t)^2*P0 + 2(1-t)t*P1 + t^2*P2
        bezier_points = (1-t)**2 * p0 + 2*(1-t)*t * p1 + t**2 * p2 # (N, 12, 2)
        
        # 2. Compute distance from every pixel to every point on the curve
        # grid: (1, 784, 2) | bezier_points: (N, 12, 2)
        # Use broadcasting to get (N, 784, 12) distances
        diff = self.grid.unsqueeze(0) - bezier_points.unsqueeze(2) # (N, 12, 784, 2)
        dist_sq = torch.sum(diff**2, dim=-1) # (N, 12, 784)
        
        # 3. Get the distance to the closest point on the curve for each pixel
        min_dist_sq, _ = torch.min(dist_sq, dim=1) # (N, 784)
        
        # 4. Apply Contrast Filter (+1 on stroke, -1 on surround)
        # Mexican Hat-like function: exp(-d^2/s1^2) - 0.5 * exp(-d^2/s2^2)
        stroke = torch.exp(-min_dist_sq / (2 * self.sigma_pos**2))
        surround = torch.exp(-min_dist_sq / (2 * self.sigma_neg**2))
        
        masks = stroke - 0.6 * surround
        return masks

    def forward(self, x):
        # x: (B, 1, 28, 28)
        B = x.size(0)
        x = x.view(B, 784)
        
        masks = self.get_masks() # (num_neurons, 784)
        
        # Linear projection using the generated masks as weights
        # Each neuron computes the dot product of input with its bezier mask
        out = torch.matmul(x, masks.t()) # (B, num_neurons)
        return out

class StrokeNet(nn.Module):
    def __init__(self, num_neurons=256):
        super().__init__()
        self.stroke_layer = StrokeNeuronLayer(num_neurons=num_neurons)
        self.classifier = nn.Sequential(
            nn.ReLU(),
            nn.Linear(num_neurons, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        h = self.stroke_layer(x)
        return self.classifier(h)

def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"--- V50: PARAMETRIC STROKE NEURONS ---")
    print(f"Device: {device}")

    # Hyperparams
    NUM_NEURONS = 256
    BATCH_SIZE = 256
    EPOCHS = 15
    LR = 0.0005 # Coordinates need a bit more push
    
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])

    train_loader = DataLoader(datasets.MNIST('./data', train=True, download=True, transform=transform), batch_size=BATCH_SIZE, shuffle=True)
    test_loader = DataLoader(datasets.MNIST('./data', train=False, transform=transform), batch_size=1024)

    model = StrokeNet(num_neurons=NUM_NEURONS).to(device)
    
    # Param count
    stroke_params = sum(p.numel() for p in model.stroke_layer.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    
    print(f"Stroke Points (Capa 1): {stroke_params} parameters (Procedural masks)")
    print(f"Total Trainable Params: {trainable_params:,}")

    optimizer = optim.Adam(model.parameters(), lr=LR)
    criterion = nn.CrossEntropyLoss()

    t_start = time.time()
    for epoch in range(1, EPOCHS + 1):
        model.train()
        t0 = time.time()
        for batch_idx, (data, target) in enumerate(train_loader):
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            
            # Constraints: keep points within [0, 28]
            with torch.no_grad():
                model.stroke_layer.points.clamp_(0, 28)

        # Eval
        model.eval()
        correct = 0
        with torch.no_grad():
            for data, target in test_loader:
                data, target = data.to(device), target.to(device)
                pred = model(data).argmax(dim=1, keepdim=True)
                correct += pred.eq(target.view_as(pred)).sum().item()

        acc = correct / 10000
        print(f"Epoch {epoch:2d} | Loss: {loss.item():.4f} | Acc: {acc:.4f} | Time: {time.time()-t0:.1f}s")

    print(f"\n🚀 Final Accuracy: {acc:.4f} | Total Time: {time.time() - t_start:.1f}s")

if __name__ == "__main__":
    main()
